# Generated by Django 4.2.29 on 2026-03-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('posting_number', models.IntegerField()),
                ('units', models.IntegerField()),
            ],
        ),
    ]
